# Generated by Django 4.2.6 on 2023-10-25 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "customerId",
                    models.CharField(max_length=64, verbose_name="Buyer ID"),
                ),
                (
                    "merchantId",
                    models.CharField(max_length=64, verbose_name="Seller ID"),
                ),
                (
                    "order_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Order Time"),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "pending"), (2, "partial"), (3, "fulfilled")]
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("GHC", "GHC ₵")], default="GHC", max_length=50
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="Note")),
            ],
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
    ]
