# Generated by Django 4.2.7 on 2023-11-27 10:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("placed_by", models.CharField(max_length=64, verbose_name="Buyer ID")),
                (
                    "placed_to",
                    models.CharField(max_length=64, verbose_name="Seller ID"),
                ),
                (
                    "order_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="Order Time"),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "PENDING"),
                            ("PARTIAL", "PARTIAL"),
                            ("FULFILLED", "FULFILLED"),
                        ],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("GHC", "GHC ₵")], default="GHC", max_length=50
                    ),
                ),
                ("note", models.TextField(blank=True, null=True, verbose_name="Note")),
            ],
        ),
        migrations.CreateModel(
            name="OrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=25),
                ),
                (
                    "tax",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "item_code",
                    models.ForeignKey(
                        default=uuid.uuid4,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="inventory.product",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="orders.order",
                        verbose_name="Order ID",
                    ),
                ),
            ],
        ),
    ]
