# Generated by Django 4.2.6 on 2023-10-26 11:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderdetail",
            name="item_code",
            field=models.ForeignKey(
                default=uuid.uuid4,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.product",
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="order",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="orders.order",
                verbose_name="Order ID",
            ),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="quantity",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=25),
        ),
        migrations.AddField(
            model_name="orderdetail",
            name="tax",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "PENDING"), (2, "PARTIAL"), (3, "FULFILLED")], default=1
            ),
        ),
    ]
