# Generated by Django 4.2.6 on 2023-10-27 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_orderdetail_item_code_orderdetail_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "PENDING"),
                    ("PARTIAL", "PARTIAL"),
                    ("FULFILLED", "FULFILLED"),
                ],
                default="PENDING",
                max_length=10,
            ),
        ),
    ]
