# Generated by Django 4.2.6 on 2023-10-27 04:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_alter_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="customerId",
            new_name="placed_by",
        ),
        migrations.RenameField(
            model_name="order",
            old_name="merchantId",
            new_name="placed_to",
        ),
    ]
