# Generated by Django 4.2.7 on 2023-12-22 14:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "transactions_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("merchant_from", models.CharField(max_length=100)),
                ("merchant_to", models.CharField(max_length=100)),
                ("key", models.CharField(max_length=512)),
                ("reference", models.CharField(max_length=100)),
                ("amount", models.PositiveIntegerField()),
                ("method", models.CharField(max_length=100)),
                ("status", models.CharField(max_length=100)),
                ("date", models.DateTimeField()),
            ],
        ),
    ]
