# Generated by Django 4.2.7 on 2023-11-17 10:29

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        (
            "inventory",
            "0003_product_category_product_description_product_volume_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Approval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "approved",
                    models.CharField(
                        choices=[
                            ("APPROVED", "APPROVED"),
                            ("PENDING", "PENDING"),
                            ("DECLINED", "DECLINED"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("issued_by", models.CharField(blank=True, max_length=100, null=True)),
                ("reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Customers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SalesZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="batch",
            old_name="volume",
            new_name="batch_volume",
        ),
        migrations.RenameField(
            model_name="batch",
            old_name="weight",
            new_name="batch_weight",
        ),
        migrations.RemoveField(
            model_name="inventoryscrap",
            name="approved",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.AddField(
            model_name="batch",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="inventoryscrap",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="inventory.productinventory",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=mptt.fields.TreeManyToManyField(blank=True, to="inventory.category"),
        ),
        migrations.AlterField(
            model_name="batch",
            name="product_inventory",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="batch",
                to="inventory.productinventory",
                verbose_name="Product",
            ),
        ),
        migrations.AlterField(
            model_name="inventoryscrap",
            name="reason",
            field=models.TextField(verbose_name="Reason for Scrap"),
        ),
        migrations.AddField(
            model_name="inventoryscrap",
            name="approval",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.approval",
            ),
        ),
        migrations.AddField(
            model_name="store",
            name="customers",
            field=models.ManyToManyField(blank=True, to="inventory.customers"),
        ),
        migrations.AddField(
            model_name="store",
            name="sale_zones",
            field=models.ManyToManyField(blank=True, to="inventory.saleszone"),
        ),
    ]
