# Generated by Django 4.2.7 on 2023-11-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0004_approval_customers_saleszone_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="batch",
            options={"verbose_name_plural": "Batches"},
        ),
        migrations.AlterModelOptions(
            name="batchstorethrough",
            options={
                "verbose_name": "Manufacter->Van",
                "verbose_name_plural": "Manufacter->Van",
            },
        ),
        migrations.AlterModelOptions(
            name="productinventory",
            options={
                "verbose_name": "Product Inventory",
                "verbose_name_plural": "Product Inventory",
            },
        ),
        migrations.RemoveField(
            model_name="batch",
            name="batch_volume",
        ),
        migrations.RemoveField(
            model_name="batch",
            name="batch_weight",
        ),
        migrations.AlterField(
            model_name="batch",
            name="batch_number",
            field=models.CharField(default="n/a", max_length=250, unique=True),
        ),
    ]
